#!/bin/sh

set -e

#DEBHELPER#

if [ "$1" != "configure" ]; then
    exit 0
fi

phpini="/etc/php53/fpm/php.ini"

ucf /usr/share/php53/php.ini-production $phpini

update-rc.d php53-fpm defaults

if [ -x /etc/init.d/php53-fpm ]
then
  if [ -f /var/run/php53-fpm.pid ] && pidof /usr/bin/php53-fpm >/dev/null
  then
    echo "Doing a soft restart"
    FPM_PID=`cat /var/run/php53-fpm.pid`
    kill -s USR2 $FPM_PID
  fi
fi

exit 0
